### ISSUE TITLE
Feature: User can create a "news" post for their feed. 

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gg-network#1]
## ⚙️ Feature

> User will be able to add text posts onto their feed. 

## 📐 Functionality

> Once the user clicks the "+" button. A modal will pop up display a text entry form where the user can write a news posting. Once the user clicks "post", it will be posted on their feed. 

## 🖼️ Wireframes

Mobile
![Screen Shot 2021-07-21 at 10 37 09 AM](https://user-images.githubusercontent.com/70422100/126534283-df0223ab-f0f5-46ac-a850-9f8221de32d4.png)\

Desktop
![Screen Shot 2021-07-21 at 10 39 53 AM](https://user-images.githubusercontent.com/70422100/126534596-5e42c2c0-0d69-4454-886b-f4256fa15d39.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] npm install needed dependencies.

**Navbar**
- [x] Within the client directory, create a component directory.
- [x] within the component dir. Create a "navBar" component.
- [x] create the navbar according to the Figma design for mobile. 
- [x] set the background- color to #252526.
- [x] set the icons to move relative to the width of the screen. 
- [x] create a @media to move the navbar to the top of the screen once it scales to the desktop view. 
- [x] add a onclick that will open the post page once the "+" button is clicked
- [ ]

**Post Form **

- [x] Create a  postForm.jsx wihtin the client/pages directory. 
- [x] create a a class component that will hold the form. 
- [x] create a constructoir witht eh state = { post: '' }
- [x] have the handlechange to get the event.target.value
- [x] create a a method "addPost+ to pos the new postings. 
- [x] create a the render()
- [x] create a div that will hold a text entry form.
- [x] add a cancel and post button after the entry form. 
- [x] export the Postform

**End Point **

- [x] in the index.js create the needed .get that will retrieve the postings
- [x] create the .post that will be recording the postings. 

**Feed Page**
- [x] create "feed page" within pages.
- [x] import the navbar component to the feedPage.jsx
- [x] create a class component that will display feed post 
- [x] within the class component create a method that will display the "li's" of the posting from the server. 

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` with the provided data.sql

### ☁️ Server

- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
