### ISSUE TITLE
Feature: User follow and see other users profiles

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gg-network#11]
## ⚙️ Feature

User can  follow and see other users profiles

## 🖼️ Wireframes

![Screen Shot 2021-07-28 at 5 57 00 PM](https://user-images.githubusercontent.com/70422100/127415135-e12957cd-4941-4d10-b37f-33d912a22119.png)
![Screen Shot 2021-07-28 at 6 00 59 PM](https://user-images.githubusercontent.com/70422100/127415391-506656fb-8065-4e1e-b095-c23872352ee5.png)

## ✅ Task List

- [ ] create a profile.jsx file
- [ ] layout out the profile to be the same as the profilePage.jsx
- [ ] style the layout to match profilepage/jsx
- [ ] set the href of `profile`
- [ ]  add the plus icon on the feed page posting
- [ ] add an event listener to the icon 
- [ ] add an event listener to the gamertag
- [ ] have is so that if the user clicks the Gamertag it will open the profile.jsx and load the user's postings
- [ ] have an event listener on the plus icon
- [ ] create an onclick that will allow user to follow
- [ ] create the fetch request to send this to the server

### 🐘 Database

- [ ] Update `data.sql` to include more dummy data
- [ ] import the new data to the db

### ☁️ Server

- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.

- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
