### ISSUE TITLE
Feature: User can Search Users and Games

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gg-network#13]
## ⚙️ Feature

User can Search Users and Games

## 🖼️ Wireframes

![Screen Shot 2021-07-29 at 3 48 46 PM](https://user-images.githubusercontent.com/70422100/127575194-b20594fa-1a74-40a3-8359-5cde09a9c664.png)

![Screen Shot 2021-07-29 at 3 49 43 PM](https://user-images.githubusercontent.com/70422100/127575275-2bfd6688-daf2-43ea-bdcd-c7ad50d3b484.png)

## ✅ Task List
*refer to the profile.jsx methods for retrieving data since it might help. 
- [x] create a search component file in the component dir.
- [x] in the file, add the class component outline
- [x] create the needed jsx for the search bar
- [x] add styling to the search bar to appear in the middle of the page.
- [x] add a method that will open and close the 
- [x] create the outline for the drop-down result.

### 🐘 Database
- [x] Update `data.sql` to  have new profiles for games accounts
- [x] import the new db

### Server

- [x] create a app.get that will filter through the server when the search is being filled.

### 🧑‍⚕️ Clean Up

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
