### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gg-network#15]
## ✅ Task List
- [ ] Run through the feature that will be tested and ensure that nothing "breaks"
- [ ] If there is an error, debug and find a solution for it.
- [ ]  Regardless of the type of network failure, users should be able to easily retry the request without navigating back to the page or re-entering a bunch of form information.
- [ ] ensure that the easter egg function run when the code is performed
