### ISSUE TITLE
User can upload image to there feed

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gg-network#3]
## 📐 Functionality

>  The user will be able to upload a photo to view on there news feed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-24 at 9 19 10 AM](https://user-images.githubusercontent.com/70422100/126874691-d9f01fef-4806-4877-a013-39f536345d90.png)

![Screen Shot 2021-07-24 at 9 20 00 AM](https://user-images.githubusercontent.com/70422100/126874709-d7e21f25-7cbb-43fd-90f7-1f8f1c349874.png)

## ✅ Task List

- [x] npm install Multer
- [x] create a file called uploads-middleware.js in the server directory.
- [ ] complete the implementation of the uploads middleware.
- [ ] Add upload middleware to the inde.js by requiring it. 
- [ ] complete the implementation on the app.post endpoint
- [ ] Verify that there are no errors when uploading an image and that uploads are being stored and recorded correctly.
- [ ] on the client-side add the implementation of uploads-middleware.
- [ ] Verify that there are no errors when uploading an image and that uploads are being stored and recorded correctly.
- [ ] create a function component that will load the images on the homepage.jsx
- [x] Edit formpage.jsx to include a file uploader

### 🐘 Database
- [ ] Confirm that the image's path is being recorded.

### ☁️ Server
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
