### ISSUE TITLE
Feature: User can delete a post

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gg-network#7]
## ⚙️ Feature

clicking the edit button will shot the image and the description, with a delete option.

## 🖼️ Wireframes
DESKTOP
<img width="946" alt="Screen Shot 2021-07-26 at 6 57 20 PM" src="https://user-images.githubusercontent.com/70422100/127082862-28ce2d02-4fb9-412e-a327-58faf4c5d072.png">

MOBILE
<img width="711" alt="Screen Shot 2021-07-26 at 7 02 07 PM" src="https://user-images.githubusercontent.com/70422100/127083267-dbd17ff4-2c53-4ae7-b958-e8346fadd9ee.png">

## ✅ Task List

- [ ] add a id to the posts with the value of there postId
- [ ] in the profilePage jsx, add the edit icon to the image
- [ ] add a click event to the button
- [ ] create a modal component file
- [ ] style the modal to the cover the page
- [ ] use div.row and div.col-half so you can have it the image on the left and the text box on the right. 
- [ ] add a div.row after the text input.
- [ ] add a div.col-half for the delete button and save button
- [ ] have the image to match by the postId
- [ ] have the description match by the postId
- [ ] create a delete modal page within components
- [ ] add the text"are you sure you want to delete and two buttons with cancel and yes/

### ☁️ Server

- [ ] Update `server/index.js` to accept delete.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
